// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUz5cJgqsyjAdICUSmjBOJO0kdgElizLc',
    appId: '1:167206730363:web:97c81d0dfdbd9f6f07c0de',
    messagingSenderId: '167206730363',
    projectId: 'flutter-to-do-41c45',
    authDomain: 'flutter-to-do-41c45.firebaseapp.com',
    storageBucket: 'flutter-to-do-41c45.firebasestorage.app',
    measurementId: 'G-4QNZDH8VP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtt4wKBFi8etul29GBNBKPWBcFfV9t13U',
    appId: '1:167206730363:android:632684d385e5baac07c0de',
    messagingSenderId: '167206730363',
    projectId: 'flutter-to-do-41c45',
    storageBucket: 'flutter-to-do-41c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAn0wJiubyOiqLERDMBtnvPJfEkAhCu3I',
    appId: '1:167206730363:ios:e02064cdd5fc938707c0de',
    messagingSenderId: '167206730363',
    projectId: 'flutter-to-do-41c45',
    storageBucket: 'flutter-to-do-41c45.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAn0wJiubyOiqLERDMBtnvPJfEkAhCu3I',
    appId: '1:167206730363:ios:e02064cdd5fc938707c0de',
    messagingSenderId: '167206730363',
    projectId: 'flutter-to-do-41c45',
    storageBucket: 'flutter-to-do-41c45.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
